M48
; DRILL file {KiCad 6.0.11-2627ca5db0~126~ubuntu20.04.1} date Tue 28 Feb 2023 05:49:02 PM WIB
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-28T17:49:02+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11-2627ca5db0~126~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X5.4032Y-3.3488
X5.6308Y-3.3488
T0
M30
